// src/lib/server/nineTakes.ts
//
// "The Chorus" — server logic for the mirror (the reflection shown the instant a
// reader crosses the give-first threshold). The evergreen question and the nine
// takes that answer it are pre-generated by scripts/generate-chorus.mjs and
// stored on the blog row + in `nine_takes`, so nothing is generated on page view.
// See docs/product/the-chorus-vision.md.

import { getSupabaseAdminClient } from '$lib/server/supabaseAdmin';
import { SmartLLMService } from '../../utils/server/smart-llm-service';
import { enneagramTypeProfiles } from '$lib/data/enneagramTypeProfiles';
import { ENNEAGRAM_TYPE_COLORS } from '$lib/constants/enneagramColors';

export type NineTake = {
	type: number; // 1..9
	archetype: string;
	take: string;
	source: 'ai' | 'human';
};

export type MirrorResult = {
	reflection: string;
	resonantType: number; // 1..9 — used only to seat the reader's take among the nine
	resonantArchetype: string;
};

const llmService = new SmartLLMService({
	httpReferer: 'https://9takes.com',
	appName: '9takes Chorus'
});

const ARCHETYPE_BY_TYPE: Record<number, string> = Object.fromEntries(
	Object.entries(enneagramTypeProfiles).map(([n, p]) => [Number(n), p.archetype])
) as Record<number, string>;

/** Compact, prompt-friendly reference of the nine emotional logics. */
function buildTypeReference(): string {
	return Object.values(enneagramTypeProfiles)
		.sort((a, b) => a.type - b.type)
		.map(
			(p) =>
				`Type ${p.type} — ${p.archetype} (${ENNEAGRAM_TYPE_COLORS[p.type]?.name ?? ''}): ` +
				`core fear = ${p.coreFear.toLowerCase()}; core desire = ${p.coreDesire.toLowerCase()}; ` +
				`core emotion = ${p.coreEmotion}.`
		)
		.join('\n');
}

function clean(text: unknown): string {
	return (text ?? '').toString().replace(/\s+/g, ' ').trim();
}

/**
 * Reflect a reader's own take back to them — the "mirror". Names the emotional
 * logic we heard. Never a verdict, never "you are a type N".
 */
export async function generateMirror(question: string, userTake: string): Promise<MirrorResult> {
	const systemPrompt = [
		'You are the mirror in 9takes. A reader has just answered a question honestly,',
		'before seeing how anyone else answered. Reflect the emotional logic you hear back',
		'to them in 2 to 3 warm, specific sentences. Name the feeling and what it is',
		'protecting or reaching for. This is recognition, not diagnosis: never tell them',
		'who they are, never use a type number or archetype name, never grade the answer.',
		'No em dashes. No therapy-speak. Talk like a perceptive friend.',
		'',
		'Separately, judge which single Enneagram emotional logic (1 through 9) the answer',
		'most resembles, for seating it among the nine. The nine logics:',
		buildTypeReference()
	].join('\n');

	const userPrompt = [
		`Question: ${question}`,
		`Their answer: ${userTake}`,
		'',
		'Return strict JSON: {"reflection": string, "resonantType": number}.'
	].join('\n');

	const raw = await llmService.getJSONResponse<{ reflection: string; resonantType: number }>({
		systemPrompt,
		userPrompt,
		profile: 'balanced',
		temperature: 0.6,
		operationType: 'chorus_mirror',
		validation: { retryOnParseError: true, maxRetries: 2 }
	});

	let resonantType = Number(raw?.resonantType);
	if (!(resonantType >= 1 && resonantType <= 9)) resonantType = 9;

	return {
		reflection: clean(raw?.reflection).slice(0, 600),
		resonantType,
		resonantArchetype: ARCHETYPE_BY_TYPE[resonantType] ?? `Type ${resonantType}`
	};
}

export type ChorusData = {
	question: string;
	/** Slug of the real `questions` row backing this chorus. */
	questionUrl: string;
	/** Id of the real `questions` row (for attaching the answer as a comment). */
	questionId: number | null;
	takes: NineTake[];
};

/** Read the evergreen question, its backing question row, and the nine takes. */
export async function getChorus(subjectSlug: string): Promise<ChorusData | null> {
	const supabase = getSupabaseAdminClient();

	const { data: person } = await (supabase as any)
		.from('blogs_famous_people')
		.select('chorus_question, chorus_question_url')
		.eq('person', subjectSlug)
		.maybeSingle();

	const question = clean(person?.chorus_question);
	const questionUrl = clean(person?.chorus_question_url);
	if (!question || !questionUrl) return null;

	const { data: row } = await (supabase as any)
		.from('nine_takes')
		.select('takes')
		.eq('subject_type', 'personality-analysis')
		.eq('subject_slug', subjectSlug)
		.maybeSingle();

	const takes = Array.isArray(row?.takes) ? (row.takes as NineTake[]) : [];
	if (takes.length !== 9) return null;

	const { data: q } = await (supabase as any)
		.from('questions')
		.select('id')
		.eq('url', questionUrl)
		.maybeSingle();

	return { question, questionUrl, questionId: q?.id ?? null, takes };
}

/** Capture the reader's take (typed corpus). Best-effort; never block the reveal. */
export async function recordUserTake(input: {
	subjectType: string;
	subjectSlug: string;
	take: string;
	resonantType: number | null;
	fingerprint: string | null;
	userId: string | null;
}): Promise<void> {
	try {
		const supabase = getSupabaseAdminClient();
		await (supabase as any).from('nine_user_takes').insert({
			subject_type: input.subjectType,
			subject_slug: input.subjectSlug,
			take: input.take.slice(0, 2000),
			resonant_type: input.resonantType,
			fingerprint: input.fingerprint,
			user_id: input.userId
		});
	} catch {
		/* swallow: corpus capture is best-effort */
	}
}
