/* eslint-disable @typescript-eslint/no-explicit-any */
export const famousTypes: { [index: number]: any[] } = {
	1: [
		{ name: 'Hillary-Clinton', link: false },
		{ name: 'Michelle-Obama', link: true },
		{ name: 'Nelson-Mandela', link: false },
		{ name: 'Ruth-Bader-Ginsburg', link: true },
		{ name: 'Steve-Jobs', link: true },
		{ name: 'Brene-Brown', link: false },
		{ name: 'Gandhi', link: false },
		{ name: 'Morgan-Freeman', link: true },
		{ name: 'Kourtney-Kardashian', link: true },
		{ name: 'Jennifer-Garner', link: true }
	],
	2: [
		{ name: 'Oprah-Winfrey', link: true },
		{ name: 'Dolly-Parton', link: false },
		{ name: 'Jimmy-Carter', link: true },
		{ name: 'Meryl-Streep', link: false },
		{ name: 'Joe-Biden', link: true },
		{ name: 'Mother-Teresa', link: false },
		{ name: 'Meghan-Markle', link: true },
		{ name: 'Nancy-Reagan', link: true },
		{ name: 'Mr-Rogers', link: true }
		// { name: 'Suzanne Stabile', link: true },
	],
	3: [
		{ name: 'Sydney-Sweeney', link: true },
		{ name: 'Kim-Kardashian', link: true },
		{ name: 'Arnold-Schwarzenegger', link: true },
		{ name: 'Ariana-Grande', link: true },
		{ name: 'Dua-Lipa', link: true },
		{ name: 'Nancy-Pelosi', link: true },
		{ name: 'Taylor-Swift', link: true },
		{ name: 'Jason-Calacanis', link: true },
		{ name: 'Reese-Witherspoon', link: false },
		{ name: 'Jake-Paul', link: true },
		{ name: 'Justin-Bieber', link: true },
		{ name: 'Tom-Cruise', link: false },
		{ name: 'Dwayne-Johnson', link: true },
		{ name: 'Addison-Rae', link: false },
		{ name: 'Kamala-Harris', link: true },
		{ name: 'Paris-Hilton', link: true },

		// { name: 'Jordan-Belfort', link: false },
		// { name: 'Matthew-Cox', link: false },
	],
	4: [
		{ name: 'Billie-Eilish', link: true },
		{ name: 'Demi-Lovato', link: true },
		{ name: 'Johnny-Depp', link: true },
		{ name: 'Charlie-Puth', link: true },
		{ name: 'Bob-Dylan', link: true },
		{ name: 'Frida-Kahlo', link: true },
		{ name: 'Lady-Gaga', link: true },
		{ name: 'Jackie-Kennedy', link: true },
		{ name: 'Elton-John', link: true },
		{ name: 'The-Weeknd', link: false },
		{ name: 'Dixie-Damelio', link: false },
		{ name: 'Nikola-Tesla', link: true },
		{ name: 'Robert-Oppenheimer', link: true },
		{ name: 'Sam-Altman', link: true },
		{ name: 'Miley-Cyrus', link: true }
		// { name: 'Ian-Cron', link: false }
	],
	5: [
		{ name: 'Bill-Gates', link: true },
		{ name: 'Elon-Musk', link: true },
		{ name: 'Jack-Dorsey', link: true },
		{ name: 'Mark-Zuckerberg', link: false },
		{ name: 'Emily-Dickinson', link: false },
		{ name: 'Stephen-Hawking', link: false },
		{ name: 'Albert-Einstein', link: false },
		{ name: 'Agatha-Christie', link: false },
		{ name: 'Rooney-Mara', link: true },
		{ name: 'Friedrich-Nietzsche', link: true },
		{ name: 'David-Sacks', link: false },
		{ name: 'Lex-Fridman', link: true },
		{ name: 'David-Friedberg', link: false }
	],
	6: [
		{ name: 'Marilyn-Monroe', link: true },
		{ name: 'Ellen-Degeneres', link: true },
		{ name: 'George-W-Bush', link: true },
		{ name: 'George-H-W-Bush', link: true },
		{ name: 'Mindy-Kaling', link: false },
		{ name: 'Mark-Twain', link: false },
		{ name: 'Prince-Harry', link: true },
		{ name: 'Peter-Thiel', link: false },
		{ name: 'Malcom-X', link: false },
		{ name: 'Khloe-Kardashian', link: true },
		{ name: 'Timothee-Chalamet', link: true },
	],
	7: [
		{ name: 'Logan-Paul', link: true },
		{ name: 'Britney-Spears', link: false },
		{ name: 'Jon-Stewart', link: true },
		{ name: 'Alex-Cooper', link: true },
		{ name: 'John-F-Kennedy', link: true },
		{ name: 'Kanye', link: true },
		{ name: 'Paul-Graham', link: true },
		{ name: 'David-Dobrik', link: true },
		{ name: 'Robin-Williams', link: false },
		{ name: 'Palmer-Luckey', link: true },
		{ name: 'Grimes', link: true },
		{ name: 'Leonardo-DiCaprio', link: true },
		{ name: 'Jimmy-Fallon', link: true }
		// { name: 'Kevin-Hart', link: false }
	],
	8: [
		{ name: 'Beyonce-Knowles', link: true },
		{ name: 'Halsey', link: true },
		{ name: 'Mr-Beast', link: true },
		{ name: 'Clint-Eastwood', link: false },
		{ name: 'Ernest-Hemingway', link: false },
		{ name: 'Martin-Luther-King-Jr', link: true },
		{ name: 'Winston-Churchill', link: true },
		{ name: 'Margot-Robbie', link: true },
		{ name: 'Chelsea-Handler', link: false },
		{ name: 'Denzel-Washington', link: true },
		{ name: 'Joe-Rogan', link: true },
		{ name: 'Dave-Portnoy', link: true },
		{ name: 'Emily-Ratajkowski', link: true }
	],
	9: [
		{ name: 'Abraham-Lincoln', link: false },
		{ name: 'Barack-Obama', link: true },
		{ name: 'Bernie-Sanders', link: true },
		{ name: 'Kylie-Jenner', link: true },
		{ name: 'Charli-DAmelio', link: false },
		{ name: 'Bella-Poarch', link: false },
		{ name: 'Marie-Kondo', link: false },
		{ name: 'Zooey-Deschanel', link: false },
		{ name: 'Pete-Davidson', link: true },
		{ name: 'Queen-Elizabeth-II', link: true },
		{ name: 'Ronald-Reagan', link: true },
		{ name: 'Keanu-Reeves', link: true }
		// { name: 'Dave-Chappelle', link: false }
	]
};
