// lib/components/molecules/famousTypes.ts
export const famousTypes: { [index: number]: any[] } = {
	1: [
		{ name: 'Hillary-Clinton', link: true },
		{ name: 'Michelle-Obama', link: true },
		{ name: 'Nelson-Mandela', link: false },
		{ name: 'Ruth-Bader-Ginsburg', link: true },
		{ name: 'Jeff-Bezos', link: true },
		{ name: 'Steve-Jobs', link: true },
		{ name: 'Brene-Brown', link: false },
		{ name: 'Gandhi', link: false },
		{ name: 'Morgan-Freeman', link: true },
		{ name: 'Kourtney-Kardashian', link: true },
		{ name: 'Jennifer-Garner', link: true },
		{ name: 'Anne-Hathaway', link: true },
		{ name: 'Emma-Watson', link: true },
		{ name: 'Natalie-Portman', link: true },
		{ name: 'Blake-Lively', link: true }
	],
	2: [
		{ name: 'Oprah-Winfrey', link: true },
		{ name: 'Dolly-Parton', link: false },
		{ name: 'Jimmy-Carter', link: true },
		{ name: 'Meryl-Streep', link: true },
		{ name: 'Joe-Biden', link: true },
		{ name: 'Mother-Teresa', link: false },
		{ name: 'Meghan-Markle', link: true },
		{ name: 'Margot-Robbie', link: true },
		{ name: 'Nancy-Reagan', link: true },
		{ name: 'Mr-Rogers', link: true },
		{ name: 'Olivia-Rodrigo', link: true },
		{ name: 'Millie-Bobby-Brown', link: true },
		{ name: 'Tom-Hiddleston', link: true },
		{ name: 'Henry-Cavill', link: true },
		{ name: 'Saoirse-Ronan', link: true },
		{ name: 'Kristen-Bell', link: true },
		{ name: 'Harry-Styles', link: true }
	],
	3: [
		{ name: 'Sydney-Sweeney', link: true },
		{ name: 'Amber-Heard', link: true },
		{ name: 'Sabrina-Carpenter', link: true },
		{ name: 'Kim-Kardashian', link: true },
		{ name: 'Arnold-Schwarzenegger', link: true },
		{ name: 'Ariana-Grande', link: true },
		{ name: 'Dua-Lipa', link: true },
		{ name: 'Nancy-Pelosi', link: true },
		{ name: 'Taylor-Swift', link: true },
		{ name: 'Jason-Calacanis', link: true },
		{ name: 'Reese-Witherspoon', link: false },
		{ name: 'Jake-Paul', link: true },
		{ name: 'Justin-Bieber', link: true },
		{ name: 'Tom-Cruise', link: true },
		{ name: 'Dwayne-Johnson', link: true },
		{ name: 'Addison-Rae', link: false },
		{ name: 'Kamala-Harris', link: true },
		{ name: 'Paris-Hilton', link: true },
		{ name: 'Will-Smith', link: true },
		{ name: 'Logan-Paul', link: true },
		{ name: 'Adin-Ross', link: true },
		{ name: 'Jenna-Ortega', link: true }
	],
	4: [
		{ name: 'Billie-Eilish', link: true },
		{ name: 'Sam-Altman', link: true },
		{ name: 'Miley-Cyrus', link: true },
		{ name: 'Lana-Del-Rey', link: true },
		{ name: 'Casey-Neistat', link: true },
		{ name: 'Demi-Lovato', link: true },
		{ name: 'Johnny-Depp', link: true },
		{ name: 'Charlie-Puth', link: true },
		{ name: 'Bob-Dylan', link: true },
		{ name: 'Frida-Kahlo', link: true },
		{ name: 'Lady-Gaga', link: true },
		{ name: 'Jackie-Kennedy', link: true },
		{ name: 'Elton-John', link: true },
		{ name: 'Dixie-Damelio', link: false },
		{ name: 'Nikola-Tesla', link: true },
		{ name: 'Robert-Oppenheimer', link: true },
		{ name: 'Prince', link: true },
		{ name: 'Joaquin-Phoenix', link: true },
		{ name: 'Robert-Pattinson', link: true },
		{ name: 'Zoe-Kravitz', link: true },
		{ name: 'Madison-Beer', link: true },
		{ name: 'Zayn-Malik', link: true },
		{ name: 'Anya-Taylor-Joy', link: true },
		{ name: 'Jerad-Leto', link: true }
	],
	5: [
		{ name: 'Bill-Gates', link: true },
		{ name: 'Elon-Musk', link: true },
		{ name: 'Jack-Dorsey', link: true },
		{ name: 'Mark-Zuckerberg', link: true },
		{ name: 'Emily-Dickinson', link: false },
		{ name: 'Stephen-Hawking', link: false },
		{ name: 'Albert-Einstein', link: false },
		{ name: 'Agatha-Christie', link: true },
		{ name: 'Rooney-Mara', link: true },
		{ name: 'Friedrich-Nietzsche', link: true },
		{ name: 'David-Sacks', link: true },
		{ name: 'Lex-Fridman', link: true },
		{ name: 'David-Friedberg', link: false },
		{ name: 'Tina-Fey', link: true },
		{ name: 'PewDiePie', link: false },
		{ name: 'Robert-Greene', link: true }
	],
	6: [
		{ name: 'Timothee-Chalamet', link: true },
		{ name: 'Alexandria-Ocasio-Cortez', link: true },
		{ name: 'Trevor-Noah', link: true },
		{ name: 'Zendaya', link: true },
		{ name: 'Prince-Harry', link: true },
		{ name: 'Peter-Thiel', link: true },
		{ name: 'Marilyn-Monroe', link: true },
		{ name: 'Ellen-Degeneres', link: true },
		{ name: 'George-W-Bush', link: true },
		{ name: 'George-H-W-Bush', link: true },
		{ name: 'Mindy-Kaling', link: false },
		{ name: 'Mark-Twain', link: false },
		{ name: 'Malcolm-X', link: false },
		{ name: 'Khloe-Kardashian', link: true },
		{ name: 'Eminem', link: true },
		{ name: 'Aubrey-Plaza', link: true },
		{ name: 'Marc-Andreessen', link: false }
	],
	7: [
		{ name: 'Kevin-Hart', link: true },
		{ name: 'Ryan-Reynolds', link: true },
		{ name: 'Katy-Perry', link: true },
		{ name: 'Britney-Spears', link: false },
		{ name: 'Jon-Stewart', link: true },
		{ name: 'Alex-Cooper', link: true },
		{ name: 'John-F-Kennedy', link: true },
		{ name: 'Kanye', link: true },
		{ name: 'Paul-Graham', link: true },
		{ name: 'David-Dobrik', link: true },
		{ name: 'Robin-Williams', link: false },
		{ name: 'Palmer-Luckey', link: true },
		{ name: 'Grimes', link: true },
		{ name: 'Leonardo-DiCaprio', link: true },
		{ name: 'Jimmy-Fallon', link: true },
		{ name: 'Tom-Holland', link: true },
		{ name: 'Miles-Teller', link: true },
		{ name: 'Hugh-Jackman', link: true },
		{ name: 'Doechii', link: true },
		{ name: 'Kai-Cenat', link: true },
		{ name: 'Robert-Downey-Jr', link: true },
		{ name: 'Jennifer-Lawrence', link: true },
		{ name: 'Emma-Chamberlain', link: true }
	],
	8: [
		{ name: 'Joe-Rogan', link: true },
		{ name: 'Dave-Portnoy', link: true },
		{ name: 'Emily-Ratajkowski', link: true },
		{ name: 'Donald-Trump', link: true },
		{ name: 'Beyonce-Knowles', link: true },
		{ name: 'Halsey', link: true },
		{ name: 'Mr-Beast', link: true },
		{ name: 'Clint-Eastwood', link: false },
		{ name: 'Ernest-Hemingway', link: false },
		{ name: 'Martin-Luther-King-Jr', link: true },
		{ name: 'Winston-Churchill', link: true },
		{ name: 'Chelsea-Handler', link: true },
		{ name: 'Denzel-Washington', link: true },
		{ name: 'Shia-LaBeouf', link: true },
		{ name: 'Rihanna', link: true },
		{ name: 'IShowSpeed', link: true },
		{ name: 'Druski', link: true },
		{ name: 'Chappell-Roan', link: true },
		{ name: 'Tom-Hardy', link: true }
	],
	9: [
		{ name: 'Selena-Gomez', link: true },
		{ name: 'Abraham-Lincoln', link: false },
		{ name: 'Barack-Obama', link: true },
		{ name: 'Bernie-Sanders', link: true },
		{ name: 'Kylie-Jenner', link: true },
		{ name: 'Charli-DAmelio', link: false },
		{ name: 'Bella-Poarch', link: false },
		{ name: 'Marie-Kondo', link: false },
		{ name: 'Zooey-Deschanel', link: false },
		{ name: 'Pete-Davidson', link: true },
		{ name: 'Queen-Elizabeth-II', link: true },
		{ name: 'Ronald-Reagan', link: true },
		{ name: 'Keanu-Reeves', link: true },
		{ name: 'Ryan-Gosling', link: true },
		{ name: 'Mikey-Madison', link: true },
		{ name: 'Brad-Pitt', link: true },
		{ name: 'Scarlett-Johansson', link: true },
		{ name: 'Dave-Chappelle', link: true },
		{ name: 'Travis-Scott', link: true }
	]
};