-- supabase/migrations/20260329_add_app_error_events.sql
-- Stores structured server-side application errors for operational debugging.

CREATE TABLE IF NOT EXISTS public.app_error_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	source TEXT NOT NULL DEFAULT 'application',
	level TEXT NOT NULL,
	message TEXT NOT NULL,
	error_name TEXT,
	error_message TEXT,
	stack TEXT,
	route TEXT,
	method TEXT,
	request_id TEXT,
	user_id TEXT,
	context JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS app_error_events_created_at_idx
	ON public.app_error_events (created_at DESC);

CREATE INDEX IF NOT EXISTS app_error_events_level_idx
	ON public.app_error_events (level, created_at DESC);

ALTER TABLE public.app_error_events ENABLE ROW LEVEL SECURITY;
