-- supabase/migrations/20260827044845_cleanup_duplicate_indexes_and_rls.sql
-- Remove non-unique indexes that exactly duplicate unique constraints.
DROP INDEX IF EXISTS public.idx_blogs_content_slug;
DROP INDEX IF EXISTS public.coaching_waitlist_email_idx;
DROP INDEX IF EXISTS public.idx_consulting_clients_email;
DROP INDEX IF EXISTS public.idx_consulting_resources_slug;
DROP INDEX IF EXISTS public.idx_email_sends_tracking_id;
DROP INDEX IF EXISTS public.idx_email_unsubscribes_email;
DROP INDEX IF EXISTS public.idx_question_tags_question_tag;

-- Keep the tiny demo table available while giving it a stable row identity.
ALTER TABLE public.use_demo_table
	ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.use_demo_table
	ADD CONSTRAINT use_demo_table_pkey PRIMARY KEY (id);

-- Harden the existing helper and make its request identity an initplan rather
-- than evaluating auth.uid() for every candidate profile row.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
	SELECT EXISTS (
		SELECT 1
		FROM public.profiles p
		WHERE p.id = (SELECT auth.uid())
			AND p.admin IS TRUE
	);
$$;

-- Consolidate exact duplicate profile policies and scope mutations to signed-in
-- users. Service-role calls continue to bypass RLS.
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile, admins can update any"
	ON public.profiles;
DROP POLICY IF EXISTS "Users can delete their own profile, admins can delete any"
	ON public.profiles;

CREATE POLICY "Public profiles are viewable by everyone"
	ON public.profiles
	FOR SELECT
	TO anon, authenticated
	USING (TRUE);

CREATE POLICY "Users can insert their own profile"
	ON public.profiles
	FOR INSERT
	TO authenticated
	WITH CHECK ((SELECT auth.uid()) = id);

CREATE POLICY "Users can update their own profile, admins can update any"
	ON public.profiles
	FOR UPDATE
	TO authenticated
	USING (
		(SELECT auth.uid()) = id
		OR (SELECT public.is_admin())
	)
	WITH CHECK (
		(SELECT auth.uid()) = id
		OR (SELECT public.is_admin())
	);

CREATE POLICY "Users can delete their own profile, admins can delete any"
	ON public.profiles
	FOR DELETE
	TO authenticated
	USING (
		(SELECT auth.uid()) = id
		OR (SELECT public.is_admin())
	);

-- Public readers need only published rows. The service role has its own role-
-- scoped policy instead of a public policy that calls deprecated auth.role().
DROP POLICY IF EXISTS "Public can read published blogs_content" ON public.blogs_content;
DROP POLICY IF EXISTS "Service role has full access to blogs_content" ON public.blogs_content;

CREATE POLICY "Public can read published blogs_content"
	ON public.blogs_content
	FOR SELECT
	TO anon, authenticated
	USING (published IS TRUE);

CREATE POLICY "Service role has full access to blogs_content"
	ON public.blogs_content
	FOR ALL
	TO service_role
	USING (TRUE)
	WITH CHECK (TRUE);
