-- supabase/migrations/20260813030000_question_feature_runs.sql
-- Controlled homepage question distribution pilot.
--
-- The homepage reads one active feature run from database state. Qualified
-- homepage impressions are deduplicated per browser fingerprint and run so a
-- run can stop at a real exposure target. Automatic queue advancement is
-- intentionally absent: when a run ends, the explicitly configured fallback
-- question is shown until an operator starts the next run.

CREATE TABLE IF NOT EXISTS public.question_distribution_settings (
	id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
	fallback_question_id BIGINT REFERENCES public.questions(id) ON DELETE SET NULL,
	default_target_unique_impressions INTEGER NOT NULL DEFAULT 30
		CHECK (default_target_unique_impressions BETWEEN 1 AND 100000),
	default_max_duration_days INTEGER NOT NULL DEFAULT 7
		CHECK (default_max_duration_days BETWEEN 1 AND 90),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

INSERT INTO public.question_distribution_settings (id, fallback_question_id)
SELECT TRUE, q.id
FROM public.questions q
WHERE q.id = 567
	AND COALESCE(q.removed, FALSE) = FALSE
	AND COALESCE(q.flagged, FALSE) = FALSE
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.question_distribution_settings (id)
VALUES (TRUE)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.question_feature_runs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE RESTRICT,
	started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ends_at TIMESTAMPTZ NOT NULL,
	ended_at TIMESTAMPTZ,
	paused_at TIMESTAMPTZ,
	reason_selected TEXT NOT NULL CHECK (CHAR_LENGTH(BTRIM(reason_selected)) BETWEEN 1 AND 500),
	selection_mode TEXT NOT NULL DEFAULT 'manual'
		CHECK (selection_mode IN ('manual', 'queue', 'fallback')),
	target_unique_impressions INTEGER NOT NULL DEFAULT 30
		CHECK (target_unique_impressions BETWEEN 1 AND 100000),
	qualified_unique_impressions INTEGER NOT NULL DEFAULT 0
		CHECK (qualified_unique_impressions >= 0),
	max_duration_days INTEGER NOT NULL DEFAULT 7
		CHECK (max_duration_days BETWEEN 1 AND 90),
	status TEXT NOT NULL DEFAULT 'active'
		CHECK (status IN ('active', 'paused', 'ended')),
	ended_reason TEXT CHECK (
		ended_reason IS NULL OR ended_reason IN (
			'impression_target',
			'duration_limit',
			'ineligible',
			'operator_stopped',
			'replaced'
		)
	),
	operator_notes TEXT CHECK (operator_notes IS NULL OR CHAR_LENGTH(operator_notes) <= 2000),
	created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CHECK (ends_at > started_at),
	CHECK ((status = 'ended') = (ended_at IS NOT NULL)),
	CHECK ((status = 'paused') = (paused_at IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_question_feature_runs_one_active
	ON public.question_feature_runs ((TRUE))
	WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_question_feature_runs_question_started
	ON public.question_feature_runs (question_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_question_feature_runs_recent
	ON public.question_feature_runs (started_at DESC);

CREATE TABLE IF NOT EXISTS public.question_feature_impressions (
	run_id BIGINT NOT NULL REFERENCES public.question_feature_runs(id) ON DELETE CASCADE,
	fingerprint_hash TEXT NOT NULL CHECK (CHAR_LENGTH(fingerprint_hash) = 64),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (run_id, fingerprint_hash)
);

ALTER TABLE public.question_distribution_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_feature_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_feature_impressions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.question_distribution_settings FROM anon, authenticated;
REVOKE ALL ON public.question_feature_runs FROM anon, authenticated;
REVOKE ALL ON public.question_feature_impressions FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_current_homepage_feature()
RETURNS TABLE (
	run_id BIGINT,
	question_id BIGINT,
	question_text TEXT,
	question_url TEXT,
	started_at TIMESTAMPTZ,
	ends_at TIMESTAMPTZ,
	target_unique_impressions INTEGER,
	qualified_unique_impressions INTEGER,
	selection_mode TEXT,
	is_fallback BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	v_run public.question_feature_runs%ROWTYPE;
BEGIN
	PERFORM pg_advisory_xact_lock(hashtext('homepage-question-feature-run'));

	UPDATE public.question_feature_runs AS r
	SET status = 'ended',
		ended_at = NOW(),
		ended_reason = CASE
			WHEN r.qualified_unique_impressions >= r.target_unique_impressions THEN 'impression_target'
			ELSE 'duration_limit'
		END,
		paused_at = NULL,
		updated_at = NOW()
	WHERE r.status = 'active'
		AND (
			r.qualified_unique_impressions >= r.target_unique_impressions
			OR r.ends_at <= NOW()
		);

	UPDATE public.question_feature_runs r
	SET status = 'ended',
		ended_at = NOW(),
		ended_reason = 'ineligible',
		paused_at = NULL,
		updated_at = NOW()
	FROM public.questions q
	WHERE r.status = 'active'
		AND q.id = r.question_id
		AND (
			COALESCE(q.removed, FALSE)
			OR COALESCE(q.flagged, FALSE)
			OR COALESCE(
				NULLIF(BTRIM(q.question_formatted), ''),
				NULLIF(BTRIM(q.question), '')
			) IS NULL
			OR NULLIF(BTRIM(COALESCE(q.url, '')), '') IS NULL
		);

	SELECT r.*
	INTO v_run
	FROM public.question_feature_runs r
	WHERE r.status = 'active'
	LIMIT 1;

	IF FOUND THEN
		RETURN QUERY
		SELECT
			v_run.id,
			q.id,
			COALESCE(NULLIF(BTRIM(q.question_formatted), ''), NULLIF(BTRIM(q.question), '')),
			q.url,
			v_run.started_at,
			v_run.ends_at,
			v_run.target_unique_impressions,
			v_run.qualified_unique_impressions,
			v_run.selection_mode,
			FALSE
		FROM public.questions q
		WHERE q.id = v_run.question_id
			AND COALESCE(q.removed, FALSE) = FALSE
			AND COALESCE(q.flagged, FALSE) = FALSE
			AND COALESCE(
				NULLIF(BTRIM(q.question_formatted), ''),
				NULLIF(BTRIM(q.question), '')
			) IS NOT NULL
			AND NULLIF(BTRIM(COALESCE(q.url, '')), '') IS NOT NULL;
		RETURN;
	END IF;

	RETURN QUERY
	SELECT
		NULL::BIGINT,
		q.id,
		COALESCE(NULLIF(BTRIM(q.question_formatted), ''), NULLIF(BTRIM(q.question), '')),
		q.url,
		NULL::TIMESTAMPTZ,
		NULL::TIMESTAMPTZ,
		s.default_target_unique_impressions,
		0,
		'fallback'::TEXT,
		TRUE
	FROM public.question_distribution_settings s
	JOIN public.questions q ON q.id = s.fallback_question_id
	WHERE s.id = TRUE
		AND COALESCE(q.removed, FALSE) = FALSE
		AND COALESCE(q.flagged, FALSE) = FALSE
		AND COALESCE(
			NULLIF(BTRIM(q.question_formatted), ''),
			NULLIF(BTRIM(q.question), '')
		) IS NOT NULL
		AND NULLIF(BTRIM(COALESCE(q.url, '')), '') IS NOT NULL
	LIMIT 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.start_question_feature_run(
	p_question_id BIGINT,
	p_reason_selected TEXT,
	p_selection_mode TEXT DEFAULT 'manual',
	p_target_unique_impressions INTEGER DEFAULT NULL,
	p_max_duration_days INTEGER DEFAULT NULL,
	p_operator_notes TEXT DEFAULT NULL,
	p_created_by UUID DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	v_settings public.question_distribution_settings%ROWTYPE;
	v_target INTEGER;
	v_days INTEGER;
	v_run_id BIGINT;
BEGIN
	PERFORM pg_advisory_xact_lock(hashtext('homepage-question-feature-run'));

	SELECT * INTO v_settings
	FROM public.question_distribution_settings
	WHERE id = TRUE;

	v_target := COALESCE(p_target_unique_impressions, v_settings.default_target_unique_impressions, 30);
	v_days := COALESCE(p_max_duration_days, v_settings.default_max_duration_days, 7);

	IF p_selection_mode NOT IN ('manual', 'queue', 'fallback') THEN
		RAISE EXCEPTION 'Invalid selection mode';
	END IF;
	IF CHAR_LENGTH(BTRIM(COALESCE(p_reason_selected, ''))) NOT BETWEEN 1 AND 500 THEN
		RAISE EXCEPTION 'Selection reason is required and must be at most 500 characters';
	END IF;
	IF v_target NOT BETWEEN 1 AND 100000 THEN
		RAISE EXCEPTION 'Impression target must be between 1 and 100000';
	END IF;
	IF v_days NOT BETWEEN 1 AND 90 THEN
		RAISE EXCEPTION 'Maximum duration must be between 1 and 90 days';
	END IF;
	IF CHAR_LENGTH(COALESCE(p_operator_notes, '')) > 2000 THEN
		RAISE EXCEPTION 'Operator notes must be at most 2000 characters';
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM public.questions q
		WHERE q.id = p_question_id
			AND COALESCE(q.removed, FALSE) = FALSE
			AND COALESCE(q.flagged, FALSE) = FALSE
			AND COALESCE(
				NULLIF(BTRIM(q.question_formatted), ''),
				NULLIF(BTRIM(q.question), '')
			) IS NOT NULL
			AND NULLIF(BTRIM(COALESCE(q.url, '')), '') IS NOT NULL
	) THEN
		RAISE EXCEPTION 'Question is not eligible to be featured';
	END IF;

	UPDATE public.question_feature_runs
	SET status = 'ended',
		ended_at = NOW(),
		ended_reason = 'replaced',
		paused_at = NULL,
		updated_at = NOW()
	WHERE status IN ('active', 'paused');

	INSERT INTO public.question_feature_runs (
		question_id,
		started_at,
		ends_at,
		reason_selected,
		selection_mode,
		target_unique_impressions,
		max_duration_days,
		operator_notes,
		created_by
	) VALUES (
		p_question_id,
		NOW(),
		NOW() + make_interval(days => v_days),
		BTRIM(p_reason_selected),
		p_selection_mode,
		v_target,
		v_days,
		NULLIF(BTRIM(COALESCE(p_operator_notes, '')), ''),
		p_created_by
	)
	RETURNING id INTO v_run_id;

	RETURN v_run_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.control_question_feature_run(
	p_run_id BIGINT,
	p_action TEXT,
	p_extension_days INTEGER DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	v_run public.question_feature_runs%ROWTYPE;
	v_pause_duration INTERVAL;
BEGIN
	PERFORM pg_advisory_xact_lock(hashtext('homepage-question-feature-run'));

	SELECT * INTO v_run
	FROM public.question_feature_runs
	WHERE id = p_run_id
	FOR UPDATE;

	IF NOT FOUND THEN
		RAISE EXCEPTION 'Feature run not found';
	END IF;

	IF p_action = 'pause' THEN
		IF v_run.status <> 'active' THEN
			RAISE EXCEPTION 'Only an active run can be paused';
		END IF;
		UPDATE public.question_feature_runs
		SET status = 'paused', paused_at = NOW(), updated_at = NOW()
		WHERE id = p_run_id;
	ELSIF p_action = 'resume' THEN
		IF v_run.status <> 'paused' OR v_run.paused_at IS NULL THEN
			RAISE EXCEPTION 'Only a paused run can be resumed';
		END IF;
		IF EXISTS (
			SELECT 1 FROM public.question_feature_runs
			WHERE status = 'active' AND id <> p_run_id
		) THEN
			RAISE EXCEPTION 'Another feature run is already active';
		END IF;
		IF NOT EXISTS (
			SELECT 1 FROM public.questions q
			WHERE q.id = v_run.question_id
				AND COALESCE(q.removed, FALSE) = FALSE
				AND COALESCE(q.flagged, FALSE) = FALSE
				AND COALESCE(
					NULLIF(BTRIM(q.question_formatted), ''),
					NULLIF(BTRIM(q.question), '')
				) IS NOT NULL
				AND NULLIF(BTRIM(COALESCE(q.url, '')), '') IS NOT NULL
		) THEN
			RAISE EXCEPTION 'Question is no longer eligible to be featured';
		END IF;
		v_pause_duration := NOW() - v_run.paused_at;
		UPDATE public.question_feature_runs
		SET status = 'active',
			paused_at = NULL,
			ends_at = ends_at + v_pause_duration,
			updated_at = NOW()
		WHERE id = p_run_id;
	ELSIF p_action = 'extend' THEN
		IF v_run.status NOT IN ('active', 'paused') THEN
			RAISE EXCEPTION 'Only an active or paused run can be extended';
		END IF;
		IF p_extension_days IS NULL OR p_extension_days NOT BETWEEN 1 AND 90 THEN
			RAISE EXCEPTION 'Extension must be between 1 and 90 days';
		END IF;
		IF v_run.max_duration_days + p_extension_days > 90 THEN
			RAISE EXCEPTION 'Total feature duration cannot exceed 90 days';
		END IF;
		UPDATE public.question_feature_runs
		SET ends_at = ends_at + make_interval(days => p_extension_days),
			max_duration_days = max_duration_days + p_extension_days,
			updated_at = NOW()
		WHERE id = p_run_id;
	ELSIF p_action = 'stop' THEN
		IF v_run.status NOT IN ('active', 'paused') THEN
			RAISE EXCEPTION 'Run has already ended';
		END IF;
		UPDATE public.question_feature_runs
		SET status = 'ended',
			ended_at = NOW(),
			ended_reason = 'operator_stopped',
			paused_at = NULL,
			updated_at = NOW()
		WHERE id = p_run_id;
	ELSE
		RAISE EXCEPTION 'Invalid feature run action';
	END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_homepage_fallback_question(
	p_question_id BIGINT,
	p_updated_by UUID DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM public.questions q
		WHERE q.id = p_question_id
			AND COALESCE(q.removed, FALSE) = FALSE
			AND COALESCE(q.flagged, FALSE) = FALSE
			AND COALESCE(
				NULLIF(BTRIM(q.question_formatted), ''),
				NULLIF(BTRIM(q.question), '')
			) IS NOT NULL
			AND NULLIF(BTRIM(COALESCE(q.url, '')), '') IS NOT NULL
	) THEN
		RAISE EXCEPTION 'Question is not eligible to be the fallback';
	END IF;

	UPDATE public.question_distribution_settings
	SET fallback_question_id = p_question_id,
		updated_at = NOW(),
		updated_by = p_updated_by
	WHERE id = TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_question_feature_impression(
	p_run_id BIGINT,
	p_question_id BIGINT,
	p_fingerprint_hash TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
	v_inserted_rows INTEGER := 0;
	v_run public.question_feature_runs%ROWTYPE;
BEGIN
	IF p_run_id IS NULL
		OR p_question_id IS NULL
		OR BTRIM(COALESCE(p_fingerprint_hash, '')) !~ '^[0-9a-f]{64}$' THEN
		RETURN FALSE;
	END IF;

	SELECT * INTO v_run
	FROM public.question_feature_runs
	WHERE id = p_run_id
	FOR UPDATE;

	IF NOT FOUND
		OR v_run.question_id <> p_question_id
		OR v_run.status <> 'active'
		OR v_run.ends_at <= NOW()
		OR v_run.qualified_unique_impressions >= v_run.target_unique_impressions THEN
		RETURN FALSE;
	END IF;

	INSERT INTO public.question_feature_impressions (run_id, fingerprint_hash)
	VALUES (p_run_id, BTRIM(p_fingerprint_hash))
	ON CONFLICT DO NOTHING;

	GET DIAGNOSTICS v_inserted_rows = ROW_COUNT;
	IF v_inserted_rows = 0 THEN
		RETURN FALSE;
	END IF;

	UPDATE public.question_feature_runs
	SET qualified_unique_impressions = qualified_unique_impressions + 1,
		updated_at = NOW()
	WHERE id = p_run_id
	RETURNING * INTO v_run;

	IF v_run.qualified_unique_impressions >= v_run.target_unique_impressions THEN
		UPDATE public.question_feature_runs
		SET status = 'ended',
			ended_at = NOW(),
			ended_reason = 'impression_target',
			paused_at = NULL,
			updated_at = NOW()
		WHERE id = p_run_id;
	END IF;

	RETURN TRUE;
END;
$$;

REVOKE ALL ON FUNCTION public.get_current_homepage_feature() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.start_question_feature_run(BIGINT, TEXT, TEXT, INTEGER, INTEGER, TEXT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.control_question_feature_run(BIGINT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_homepage_fallback_question(BIGINT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_question_feature_impression(BIGINT, BIGINT, TEXT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.get_current_homepage_feature() TO service_role;
GRANT EXECUTE ON FUNCTION public.start_question_feature_run(BIGINT, TEXT, TEXT, INTEGER, INTEGER, TEXT, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.control_question_feature_run(BIGINT, TEXT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_homepage_fallback_question(BIGINT, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_question_feature_impression(BIGINT, BIGINT, TEXT) TO service_role;
